Feature/demo flow
Tomgroot/whosetrack-api pull request #2
Opened 2024-09-29 14:49 UTC by Casvharen

2024-09-29 19:46 UTC, Tomgroot requested changes

2024-09-29 19:46 UTC, Tomgroot commented on app/Http/Controllers/UserController.php
> +        if ($request->get('nickname') == 'Demo user 1') {
Lets add an env for 'Demo user 1' as well. $_ENV['DEMO_USER_NAME']

2024-09-29 19:46 UTC, Tomgroot commented on app/Models/Round.php
> +                if($this->id == $_ENV['DEMO_ROUND_ID_1'] || $this->id == $_ENV['DEMO_ROUND_ID_2']){
why the double if statement?

2024-09-29 19:46 UTC, Tomgroot commented on app/Models/Round.php
> +            if($this->id == $_ENV['DEMO_ROUND_ID_1'] || $this->id == $_ENV['DEMO_ROUND_ID_2']){
maybe move this logic to $this->demoOnGuessWhose() or something similar to keep this function clean.

2024-09-29 19:46 UTC, Tomgroot commented on app/Models/Round.php
> +            if($this->id == $_ENV['DEMO_ROUND_ID_1'] || $this->id == $_ENV['DEMO_ROUND_ID_2']){
also for this maybe a `$this->demoOnStatusFinished()`

2024-09-29 19:46 UTC, Tomgroot commented on database/seeders/DatabaseSeeder.php
> +            'id' => $_ENV['DEMO_USER_ID'],
I am also thinking, we could even move the vars out of the environment (because this won't be different in different environments right?), why not create static constants inside the User model, which we can use everywhere we need it?

2024-10-01 19:02 UTC, Casvharen commented
Comments are processed, so ready to merge

2024-10-16 16:48 UTC, merged